#ifndef STATETYPE_H
#define STATETYPE_H

enum StateType {
	STATE_BEGIN=1,
	STATE_COMMENTARY,
	STATE_NUMBER,
	STATE_NEGATE,
	STATE_EQUALITY,
	STATE_INEQUALITY,
	STATE_WORD,
	STATE_STRING,
	STATE_HVAR_OR_RAMAINER,
	STATE_SVAR_OR_LVAR,
	STATE_XVAR_WORD,
	STATE_END_UNKNOWNTYPE,
	STATE_END_KNOWNTYPE,
};

#endif /* STATETYPE_H */
